# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Clenup work dir
      run: |
        sudo rm -r -d /home/ubuntu/iforecast-back-runner/_work/iforecast-back/iforecast-back/*
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        source /home/ubuntu/iforecast-back-runner/_work/iforecast-back/iforecast-back-env/bin/activate
        sudo systemctl stop iforecast_back_api
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo systemctl start iforecast_back_api
